# Bitcoin donation for this project
custom: ["bitcoin:bc1qwh9k7rlkgj0qfw8wgvqmj86h5m5ddphph2lzg3af0x5p5h9s6qms7a6aqp", "https://blockchain.info/address/bc1qwh9k7rlkgj0qfw8wgvqmj86h5m5ddphph2lzg3af0x5p5h9s6qms7a6aqp"]

